name: front_vision_assistant
description: "Vision Assistant for visually impaired users."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  elevenlabs_flutter: ^0.0.1
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.36
  just_audio_web: ^0.4.9
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  speech_to_text: ^6.6.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
